### ISSUE TITLE
/player/:tag and /band/:tag not working

### ISSUE THREAD

**Issue by SharpBit** [uyti/brawl-api#1]
I'm trying to access my player info (GGJVJLU2) and band info (QCGVPV8) but both give me this: https://gyazo.com/65b9ffdd5a3b7b875d3513c657c20b41

idk the error but it says to check ur application logs

**Comment by SharpBit** [comment]
@uyti please answer

**Comment by uyti** [comment]
I'm investigating the issue, sorry :(

Will provide updates on this thread

**Comment by uyti** [comment]
Issue has been located. Will fix as soon as I can.

**Comment by SharpBit** [comment]
Any updates?

**Comment by uyti** [comment]
Hello! I wanted to release the API into prod today after the past week of testing, however the update set me back :(

**Comment by uyti** [comment]
Sorry for the lack of ETA

**Comment by SharpBit** [comment]
@uyti any updates?
